/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Janidu
 */
public class DeleteStuForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteStuForm.class.getName());

    /**
     * Creates new form DeleteStuForm
     */
    public DeleteStuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddStudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        btnBackToHome = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtStudentID = new javax.swing.JTextField();
        lblStuName = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        lblNicNum = new javax.swing.JLabel();
        txtNicNum = new javax.swing.JTextField();
        lblPrfMarks = new javax.swing.JLabel();
        txtPrfMarks = new javax.swing.JTextField();
        lblDbmsMarks = new javax.swing.JLabel();
        txtDbmsMarks = new javax.swing.JTextField();

        btnAddStudent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(this::btnAddStudentActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete Student");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" iCET - Institute of Computer Engineering Technology");

        btnDelete.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDelete.setText("Delete Student");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnCancle.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCancle.setText("Cancle");
        btnCancle.addActionListener(this::btnCancleActionPerformed);

        btnBackToHome.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        btnBackToHome.setText("←");
        btnBackToHome.addActionListener(this::btnBackToHomeActionPerformed);

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        lblStuName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblStuName.setText("Name");
        lblStuName.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblStuNameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNicNum.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblNicNum.setText("NIC Number");

        txtNicNum.addActionListener(this::txtNicNumActionPerformed);

        lblPrfMarks.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblPrfMarks.setText("PRF Marks");

        txtPrfMarks.addActionListener(this::txtPrfMarksActionPerformed);

        lblDbmsMarks.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblDbmsMarks.setText("DBMS Marks");

        txtDbmsMarks.addActionListener(this::txtDbmsMarksActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnSearch))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDbmsMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrfMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDbmsMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPrfMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStuName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStuName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNicNum)
                    .addComponent(txtNicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrfMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrfMarks))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDbmsMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDbmsMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnCancle))
                    .addComponent(btnBackToHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed

        
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        String userInputRegID = txtStudentID.getText();
        for (Students student : StudentCollection.studentsArray) {
            if (student != null && student.studentId.equals(userInputRegID)) {
                int index = java.util.Arrays.asList(StudentCollection.studentsArray).indexOf(student);
                StudentCollection.studentsArray[index] = null;
                JOptionPane.showMessageDialog(null,"Successfully Deleted " + userInputRegID);
                break;
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        txtStuName.setText(null);
        txtNicNum.setText(null);
        txtPrfMarks.setText(null);
        txtDbmsMarks.setText(null);
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        new StudentPage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String userInputRegID = txtStudentID.getText();
        for (Students studentsArray : StudentCollection.studentsArray) {
            if (studentsArray.studentId .equals (userInputRegID)) {
                txtStuName.setText(studentsArray.getStuName());
                txtNicNum.setText(studentsArray.getStuNic());
                txtPrfMarks.setText(String.valueOf(studentsArray.getPrfMarks()));
                txtDbmsMarks.setText(String.valueOf(studentsArray.getDbmsMarks()));
                break;
            }else{
                JOptionPane.showMessageDialog(null, "Invaild Registration ID");
            }
            break;
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtNicNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicNumActionPerformed

    private void txtPrfMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrfMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrfMarksActionPerformed

    private void txtDbmsMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDbmsMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDbmsMarksActionPerformed

    private void lblStuNameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblStuNameAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStuNameAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeleteStuForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDbmsMarks;
    private javax.swing.JLabel lblNicNum;
    private javax.swing.JLabel lblPrfMarks;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JTextField txtDbmsMarks;
    private javax.swing.JTextField txtNicNum;
    private javax.swing.JTextField txtPrfMarks;
    private javax.swing.JTextField txtStuName;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
