/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagementsystem;

/**
 *
 * @author Janidu
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStuManagement = new javax.swing.JButton();
        btnBatchManagement = new javax.swing.JButton();
        btnGradeManagement = new javax.swing.JButton();
        btnReportGenerator = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Management System");

        btnStuManagement.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnStuManagement.setText("Student Mangement");
        btnStuManagement.addActionListener(this::btnStuManagementActionPerformed);

        btnBatchManagement.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnBatchManagement.setText("Batch Mangement");
        btnBatchManagement.addActionListener(this::btnBatchManagementActionPerformed);

        btnGradeManagement.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnGradeManagement.setText("Grade Mangement");
        btnGradeManagement.addActionListener(this::btnGradeManagementActionPerformed);

        btnReportGenerator.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnReportGenerator.setText("Report Generator");
        btnReportGenerator.addActionListener(this::btnReportGeneratorActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" iCET - Institute of Computer Engineering Technology");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnStuManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnBatchManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnGradeManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnReportGenerator, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnStuManagement)
                .addGap(34, 34, 34)
                .addComponent(btnBatchManagement)
                .addGap(34, 34, 34)
                .addComponent(btnGradeManagement)
                .addGap(34, 34, 34)
                .addComponent(btnReportGenerator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuManagementActionPerformed
        new StudentPage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnStuManagementActionPerformed

    private void btnBatchManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatchManagementActionPerformed
        new BtachMode().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBatchManagementActionPerformed

    private void btnGradeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeManagementActionPerformed
       new GradeManagementModeForm().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnGradeManagementActionPerformed

    private void btnReportGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportGeneratorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportGeneratorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatchManagement;
    private javax.swing.JButton btnGradeManagement;
    private javax.swing.JButton btnReportGenerator;
    private javax.swing.JButton btnStuManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    

}
